FUNCTION fncNumerico RETURN LOGICAL (INPUT p_var AS CHARACTER):
    DEFINE VARIABLE vLoop AS INTEGER NO-UNDO.
    DO vLoop = 1 TO LENGTH(p_var):
        IF INDEX('0123456789':U,SUBSTRING(p_var,vLoop,1)) = 0 THEN RETURN NO.
    END.
    RETURN YES.
END FUNCTION.
