DEF VAR P-RESP AS CHAR.

FIND FIRST AMKT-SOLICITACAO WHERE AMKT-SOLICITACAO.NUMERO = 6402 NO-ERROR.
ASSIGN AMKT-SOLICITACAO.SITUACAO-PAGTO = "sOLICITA€ÇO pAGTO. lIBERADA".
RUN ESP\CRIAPAGTOSOLICMKT.P(INPUT "3fad9cd3498e1c43d2d08364bb5bd3d9",
                            INPUT 808,
                            INPUT 6402,
                            INPUT 1200,
                            INPUT "TESTEW",
                            OUTPUT P-RESP).

MESSAGE P-RESP VIEW-AS ALERT-BOX.