OUTPUT TO c:\temp\cd0309.txt.
DEF VAR o AS CHAR EXTENT 8.

PUT UNFORMATTED "nat-operacao"                             ";"         
                "it-codigo"                                ";"
                'cod-depos'                                ";"
                "cod-canal-venda"                          ";"
                "serie"                                    ";"
                "fm-com"                                   ";"
                "no-ab-repre"                              ";"
                "ge-codigo"                                ";"
                "cod-estabel"                              ";"
                "cod-gr-cli"                               ";"
                'fm-codigo'                                ";"
                'ct-recven'                                ";"
                'sc-recven'                                ";"
                'ct-cusven'                                ";"
                'sc-cusven'                                ";"
                'ct-icms-ft'                               ";"
                'sc-icms-ft'                               ";"
                'ct-ipi-ft'                                ";"
                'sc-ipi-ft'                                ";"
                'ct-iss-ft'                                ";"
                'sc-iss-ft'                                ";"
                'ct-ir-ret'                                ";"
                'sc-ir-ret'                                ";"
                'ct-icmsub-ft'                             ";"
                'sc-icmsub-ft'                             ";"
                'sc-cofins-ft'                             ";"
                'ct-cofins-ft'                             ";"
                'ct-pis-ft'                                ";"
                'sc-pis-ft'                                ";"
                'ct-despesa'                               ";"
                'ct-frete-ft'                              ";"
                'ct-diversos-ft'                           ";"
                'conta-dev-cpv'                            ";"
                'conta-dev-rec'                            ";"
                'Ct-desp-fretes'                           ";"
                'Sc-desp-fretes'                           ";"
                'cod-dev-prod'                             ";"
                'cod-ct-inss'                              ";"
                'cod-ct-pis'                               ";"
                'cod-ct-cofins'                            ";"
                'cod-cta-retenc-csll'                      ";"
                'cod-cta-retenc-pis'                       ";"
                'cod-cta-retenc-cofins'                    ";"
                'cod-cta-recta-export-nao-embarc'          ";"
                'cod-ccusto-recta-export-nao-emb'          ";"
                'cod-ccusto-retenc-cofins'                 ";"
                'cod-ccusto-retenc-csll'                   ";"
                'cod-ccusto-retenc-pis'                    ";"
                'cod-cta-devol-cpv'                        ";"
                'cod-ccusto-devol-cpv'                     ";"
                'cod-cta-devol-recta'                      ";"
                'cod-ccusto-devol-recta'                   ";"
                'cod-cta-desc'                             ";"
                'cod-ccusto-desc'                          ";"
                'cod-cta-diver'                            ";"
                'cod-ccusto-diver'                         ";"
                'cod-cta-frete'                            ";"
                'cod-ccusto-frete'                         ";"
                'cod-cta-irrf'                             ";"
                'cod-cta-despes-iss'                       ";"
                'cod-cta-devol-produc'                     ";"
                'cod-ccusto-devol-produc'                  ";"
                'cod-cta-inss-retid'                       ";"
               'cod-ccusto-inss-retid'                     ";"
                'cod-cta-pis'                              ";"
                'cod-ccusto-pis'                           ";"
                'cod-cta-cofins'                           ";"
                'cod-ccusto-cofins'                        ";"
                'cod-cta-retenc-iss'                       ";"
                'cod-ccusto-retenc-iss'                    ";"
                'cod-cta-despes-icms-sub'                  ";"
                'cod-cta-cust-produt-vendido'              ";"
                'cod-cta-despes-recta-vda'                 ";"
                'cod-cta-ctbl-despes-icms'                 ";"
                'cod-cta-ctbl-despes-ipi'                  ";"
                'cod-cta-ctbl-despes-frete'                ";"
                'cod-cta-ctbl-retenc-csll'                 ";"
                'cod-cta-ctbl-retenc-pis'                  ";"
                'cod-cta-ctbl-retenc-cofins'               ";"
                'cod-cta-ctbl-recta-export-nao-em'         ";"
                'cod-cta-ctbl-retenc-iss'                  ";"
                'cod-cta-ctbl-despes-pis-subst'            ";"
                'cod-cta-ctbl-despes-cofins-subst'         ";"
                'Difal'                                    ";"
                'Difal'                                    ";"
                'Difal'                                    
    SKIP.


FOR EACH conta-ft:

       
        ASSIGN O[1] = IF conta-ft.cod-estabel = ? THEN "" ELSE conta-ft.cod-estabel.
        ASSIGN O[2] = IF STRING(conta-ft.cod-gr-cli) = ? THEN "" ELSE STRING(conta-ft.cod-gr-cli).
        ASSIGN O[3] = IF STRING(conta-ft.cod-canal-venda) = ? THEN "" ELSE STRING(conta-ft.cod-canal-venda).
        ASSIGN O[4] = IF STRING(conta-ft.ge-codigo) = ? THEN "" ELSE STRING(conta-ft.ge-codigo).
        ASSIGN O[5] = IF STRING(conta-ft.fm-codigo) = ? THEN "" ELSE STRING(conta-ft.fm-codigo).
        ASSIGN O[6] = IF conta-ft.nat-operacao = ? THEN "" ELSE conta-ft.nat-operacao.
        ASSIGN O[7] = IF conta-ft.serie = ? THEN "" ELSE conta-ft.serie.
        ASSIGN o[8] = o[1] + CHR(2) + o[2] + CHR(2) + o[3] + CHR(2) + o[4] + CHR(2) + o[5] + CHR(2) + o[6] + CHR(2) + o[7].

        FIND FIRST inf-compl WHERE inf-compl.cod-indice = o[8]
                             AND   inf-compl.cdn-identif = 17 NO-ERROR.


  PUT UNFORMATTED  conta-ft.nat-operacao                           ";"
                   conta-ft.it-codigo                              ";"
                   conta-ft.cod-depos                              ";"
                   conta-ft.cod-canal-venda                        ";"
                   conta-ft.serie                                  ";"
                   conta-ft.fm-com                                 ";"
                   conta-ft.no-ab-repre                            ";"
                   conta-ft.ge-codigo                              ";"
                   conta-ft.cod-estabel                            ";"
                   conta-ft.cod-gr-cli                             ";"
                   conta-ft.fm-codigo                              ";"
                   conta-ft.ct-recven                              ";"
                   conta-ft.sc-recven                              ";"
                   conta-ft.ct-cusven                              ";"
                   conta-ft.sc-cusven                              ";"
                   conta-ft.ct-icms-ft                             ";"
                   conta-ft.sc-icms-ft                             ";"
                   conta-ft.ct-ipi-ft                              ";"
                   conta-ft.sc-ipi-ft                              ";"
                   conta-ft.ct-iss-ft                              ";"
                   conta-ft.sc-iss-ft                              ";"
                   conta-ft.ct-ir-ret                              ";"
                   conta-ft.sc-ir-ret                              ";"
                   conta-ft.ct-icmsub-ft                           ";"
                   conta-ft.sc-icmsub-ft                           ";"
                   conta-ft.sc-cofins-ft                           ";"
                   conta-ft.ct-cofins-ft                           ";"
                   conta-ft.ct-pis-ft                              ";"
                   conta-ft.sc-pis-ft                              ";"
                   conta-ft.ct-despesa                             ";"
                   conta-ft.ct-frete-ft                            ";"
                   conta-ft.ct-diversos-ft                         ";"
                   conta-ft.conta-dev-cpv                          ";"
                   conta-ft.conta-dev-rec                          ";"
                   conta-ft.Ct-desp-fretes                         ";"
                   conta-ft.Sc-desp-fretes                         ";"
                   conta-ft.cod-dev-prod                           ";"
                   conta-ft.cod-ct-inss                            ";"
                   conta-ft.cod-ct-pis                             ";"
                   conta-ft.cod-ct-cofins                          ";"
                   conta-ft.cod-cta-retenc-csll                    ";"
                   conta-ft.cod-cta-retenc-pis                     ";"
                   conta-ft.cod-cta-retenc-cofins                  ";"
                   conta-ft.cod-cta-recta-export-nao-embarc        ";"
                   conta-ft.cod-ccusto-recta-export-nao-emb        ";"
                   conta-ft.cod-ccusto-retenc-cofins               ";"
                   conta-ft.cod-ccusto-retenc-csll                 ";"
                   conta-ft.cod-ccusto-retenc-pis                  ";"
                   conta-ft.cod-cta-devol-cpv                      ";"
                   conta-ft.cod-ccusto-devol-cpv                   ";"
                   conta-ft.cod-cta-devol-recta                    ";"
                   conta-ft.cod-ccusto-devol-recta                 ";"
                   conta-ft.cod-cta-desc                           ";"
                   conta-ft.cod-ccusto-desc                        ";"
                   conta-ft.cod-cta-diver                          ";"
                   conta-ft.cod-ccusto-diver                       ";"
                   conta-ft.cod-cta-frete                          ";"
                   conta-ft.cod-ccusto-frete                       ";"
                   conta-ft.cod-cta-irrf                           ";"
                   conta-ft.cod-cta-despes-iss                     ";"
                   conta-ft.cod-cta-devol-produc                   ";"
                   conta-ft.cod-ccusto-devol-produc                ";"
                   conta-ft.cod-cta-inss-retid                     ";"
                   conta-ft.cod-ccusto-inss-retid                  ";"
                   conta-ft.cod-cta-pis                            ";"
                   conta-ft.cod-ccusto-pis                         ";"
                   conta-ft.cod-cta-cofins                         ";"
                   conta-ft.cod-ccusto-cofins                      ";"
                   conta-ft.cod-cta-retenc-iss                     ";"
                   conta-ft.cod-ccusto-retenc-iss                  ";"
                   conta-ft.cod-cta-despes-icms-sub                ";"
                   conta-ft.cod-cta-cust-produt-vendido            ";"
                   conta-ft.cod-cta-despes-recta-vda               ";"
                   conta-ft.cod-cta-ctbl-despes-icms               ";"
                   conta-ft.cod-cta-ctbl-despes-ipi                ";"
                   conta-ft.cod-cta-ctbl-despes-frete              ";"
                   conta-ft.cod-cta-ctbl-retenc-csll               ";"
                   conta-ft.cod-cta-ctbl-retenc-pis                ";"
                   conta-ft.cod-cta-ctbl-retenc-cofins             ";"
                   conta-ft.cod-cta-ctbl-recta-export-nao-em       ";"
                   conta-ft.cod-cta-ctbl-retenc-iss                ";"
                   conta-ft.cod-cta-ctbl-despes-pis-subst          ";"
                   conta-ft.cod-cta-ctbl-despes-cofins-subst       ";"
                   inf-compl.des-campo                             ";"
                   inf-compl.cod-livre-1                           ";"
                   inf-compl.cod-livre-2                           ";"
      SKIP.






END.
